name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^4.1.3
  firebase_core: any
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  cloud_firestore: any
  flutter_svg: ^1.1.6
  emoji_picker_flutter: ^1.5.1
  image_picker: ^0.8.6
  firebase_storage: ^11.0.6
  uuid: ^3.0.7
  firebase_messaging: any
  flutter_local_notifications: ^9.4.0
  http: ^0.13.5
  rxdart: ^0.27.7
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets: 
    - assets/images/
