// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWzPiXVPQjfJaLGPb3A5wt1JcLamx-8nk',
    appId: '1:346079764494:web:f8cc90674e0750e609dc5f',
    messagingSenderId: '346079764494',
    projectId: 'chatapp-598f3',
    authDomain: 'chatapp-598f3.firebaseapp.com',
    storageBucket: 'chatapp-598f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz11YHGUlu4JBRc6YhxpVhEkQCQlqX2zg',
    appId: '1:346079764494:android:82ba3198e92b84b009dc5f',
    messagingSenderId: '346079764494',
    projectId: 'chatapp-598f3',
    storageBucket: 'chatapp-598f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbCu5Bbw9-gMX3Eg9N0OGVJVHVMFoYL6M',
    appId: '1:346079764494:ios:793d29b2650cc8fa09dc5f',
    messagingSenderId: '346079764494',
    projectId: 'chatapp-598f3',
    storageBucket: 'chatapp-598f3.appspot.com',
    iosClientId: '346079764494-5psc6i2aiqc00l4jkakhgkqevfvve4pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbCu5Bbw9-gMX3Eg9N0OGVJVHVMFoYL6M',
    appId: '1:346079764494:ios:793d29b2650cc8fa09dc5f',
    messagingSenderId: '346079764494',
    projectId: 'chatapp-598f3',
    storageBucket: 'chatapp-598f3.appspot.com',
    iosClientId: '346079764494-5psc6i2aiqc00l4jkakhgkqevfvve4pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
